name: movie-box
on:
  push:
    branches: develop
  schedule:
    - cron: '0 0 * * *'
  watch: 
    types: [started]
jobs:
  moviebox:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v2
     - run: npm install
     - name: Update 
       uses: ./
       env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: ${{ secrets.GIST_ID }}
          TRAKT_ID: ${{ secrets.TRAKT_ID }}
          TRAKT_USERNAME: ${{ secrets.TRAKT_USERNAME }}
          MOVIE_BOX_MODE: ${{ secrets.MOVIE_BOX_MODE }}
